steps:
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        npm install
        npm run build
        firebase deploy --project=mmm-nevo --token=${_FIREBASE_TOKEN}
    
options:
  logging: CLOUD_LOGGING_ONLY
